[advisories]
# RUSTSEC-2023-0071: RSA Marvin Attack vulnerability
# This is a transitive dependency from sqlx-mysql, which we don't use.
# We only use sqlx with PostgreSQL (sqlx/postgres feature).
ignore = ["RUSTSEC-2023-0071"]
